spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codelily?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: rootpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate          # Flyway로 관리하므로 자동 생성 금지
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100  # 성능 최적화

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.codelily.backend.domain
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false        # Redis 캐싱 전략을 쓰므로 MyBatis 자체 캐시는 비활성화
      jdbc-type-for-null: 'NULL'  # NULL 처리 안정화

  flyway:
    enabled: true
    baseline-on-migrate: true     # 기존 DB 스키마가 있어도 마이그레이션 가능
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}             # 환경 변수로 관리
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: [openid, profile, email]

          kakao:
            client-id: ${KAKAO_CLIENT_ID}             # 환경 변수로 관리
            client-secret: ""
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: [account_email, profile_nickname, profile_image]

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id   # 카카오는 'id'를 고유키로 사용

# JWT 관련 설정 추가
jwt:
  secret: ${JWT_SECRET}           # 환경 변수에서 관리 (노출 방지)
  access-token-expiration: 1800000    # AccessToken 만료 시간 (30분, ms 단위)
  refresh-token-expiration: 604800000 # RefreshToken 만료 시간 (7일, ms 단위)

# OAuth2 로그아웃 리디렉트 설정
oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    logout-redirect-uri: http://localhost:3000/auth/logout-success
  google:
    logout-redirect-uri: http://localhost:3000/auth/logout-success

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.mybatis: debug
    org.springframework.security: debug
